title: Ting Tar Tid
email: kyrremann@gmail.com
url: "https://tingtartid.beer"
untappd_brewery_id: "413148"

# Build settings
markdown: kramdown
permalink: pretty
encoding: UTF-8
timezone: Europe/Oslo
