# Site settings
title: Ting Tar tid
email: kyrremann@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A small home brewery called Ting Tar Tid.
baseurl: "/tingtartid" # the subpath of your site, e.g. /blog
url: "https://kyrremann.github.io" # the base hostname & protocol for your site
twitter_username: 2k3
github_username:  kyrremann

# Build settings
markdown: kramdown
permalink: pretty
