title: Ting Tar Tid
email: kyrremann@gmail.com
description: et lite hjemmebryggeri som fokuserer på mørk, kraftig, og alternativ øl
url: "https://tingtartid.beer"
untappd_brewery_name: "tingtartid"

# Build settings
markdown: kramdown
permalink: pretty
encoding: UTF-8
timezone: Europe/Oslo
permalink: /:year/:month/:day/:title

collections:
  batches:
    output: true
    permalink: /batch/:name
